ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('get_order_total/', views.getOrderTotal, name='get_order_total'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('process_order/', views.processOrder, name='process_order'),
    path('register/', views.registerView, name='register'),
    path('show_detail/', views.showDetail, name='show_detail'),
    path('update_item/', views.updateItem, name='update_item'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    description = models.TextField(
        default='No description', null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    @property  # decorator untuk membuat property sebuah class
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = 'https://via.placeholder.com/640x360.png'
        return url


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=255, null=True)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()

        for i in orderitems:
            if i.product.digital == False:
                shipping = True

        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_item(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    zipcode = models.CharField(max_length=255, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import Http404
from django.db.models import Q
import json
import datetime

from .models import *
from .utils import cookieCart, cartData, guestOrder, makePayment, productPaginator

# Create your views here.


def store(request):

    data = cartData(request)
    cartItems = data['cartItems']

    if request.GET.get('search'):
        search = request.GET.get('search')
        product_list = Product.objects.filter(name__icontains=search)
    else:
        product_list = Product.objects.all()
        search = False

    per_page = 9
    number_paginator = 2

    product_pagination = productPaginator(
        request, product_list, per_page, number_paginator)

    context = {
        'products': product_pagination['products'],
        'cartItems': cartItems,
        'start': product_pagination['start'],
        'end': product_pagination['end'],
        'page': product_pagination['page'],
        'show_page_num': range(product_pagination['start'], product_pagination['end']+1),
        'total_page': product_pagination['total_page'],
    }

    if search:
        context['search'] = search

    return render(request, 'store/store.html', context)


def cart(request):

    data = cartData(request)
    order = data['order']
    items = data['items']
    cartItems = data['cartItems']

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'store/cart.html', context)


def checkout(request):

    data = cartData(request)
    order = data['order']
    items = data['items']
    cartItems = data['cartItems']

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        orderItem.quantity += 1
    elif action == 'remove':
        orderItem.quantity -= 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    try:
        quantity = orderItem.quantity
    except OrderItem.DoesNotExist:
        quantity = 0

    total_item = order.get_cart_item
    total_price = order.get_cart_total

    json_response = {
        'total_item': total_item,
        'quantity': quantity,
        'total': total_price,
        'item_price': orderItem.get_total
    }

    return JsonResponse(json_response, safe=False)


def processOrder(request):
    data = json.loads(request.body)
    transaction_id = datetime.datetime.now().timestamp()

    if request.method == 'POST':
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(
                customer=customer, complete=False)
        else:
            customer, order = guestOrder(request, data)

        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True

        order.save()

        if order.shipping == True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode']
            )

        payment_data = {
            'order_id': order.transaction_id,
            'gross_amount': order.get_cart_total,
            'name': customer.name,
            'email': customer.email,
        }

        token = makePayment(request, payment_data)

    return JsonResponse({'token': token}, safe=False)


def loginView(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        try:
            user = get_user_model().objects.get(email=email)
            username = user.username
        except:
            username = ''

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('store:store')
        else:
            messages.error(request, 'Login invalid')
            return redirect('store:store')


def registerView(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        name = request.POST['name']
        password = request.POST['password']

        user, created = get_user_model().objects.get_or_create(username=username)
        if created:
            user.email = email
            user.set_password(user.password)
            user.save()

        customer, created = Customer.objects.get_or_create(email=email)
        customer.name = name
        customer.user = user
        customer.save()

        login(request, user)

        return redirect('store:store')


def logoutView(request):
    logout(request)

    return redirect(('store:store'))


def showDetail(request):
    product = Product.objects.get(id=request.GET.get('id'))

    product_json = serializers.serialize('python', [product])

    return JsonResponse(product_json, safe=False)


def getOrderTotal(request):
    data = json.loads(request.body)
    total_harga = 0
    total_item = 0

    for key, value in data.items():
        productId = int(key)
        harga_product = Product.objects.get(id=productId).price
        total_harga += (harga_product*value['quantity'])
        total_item += value['quantity']

    json_data = {
        'total_price': int(total_harga),
        'total_item': total_item,
    }

    return JsonResponse(json_data, safe=False)

store/templates/store/snippets/auth.html
<!-- Modal Login -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'store:login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                            aria-describedby="emailHelp">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                            else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="">
                        <small class="float-left">Don't have an account yet? <a id="register-anchor" data-toggle="modal"
                                data-target="#registerModal" data-dismiss="modal" aria-label="Close"
                                class="text-primary" href="">Create new one</a>
                        </small>
                        <button type="submit" class="btn btn-primary float-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal Register -->
<div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Register</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'store:register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                            aria-describedby="emailHelp">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                            else.</small>
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input name="username" type="text" class="form-control" id="username">
                    </div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input name="name" type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="">
                        <button type="submit" class="btn btn-primary float-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Modal Logout -->
<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Logout Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Please confirm your logout request
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="{% url 'store:logout' %}" class="btn btn-primary">Confirm</a>
            </div>
        </div>
    </div>
</div>

store/templates/store/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'store:store' %}"><img height="40px"
            src="{% static 'store/img/mykedailogo.png' %}" class="float-left" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
        </ul>

        <div class="form-inline my-2 my-lg-0">

            {% if user.is_authenticated %}
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#logoutModal">
                Logout
            </button>
            {% else %}
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#loginModal">
                Login
            </button>
            {% endif %}


            <a href="{% url 'store:cart' %}">
                <img src="{% static 'store/img/cart.png' %}" id="cart-icon" alt="">
            </a>
            <p id="cart-total">{{cartItems}}</p>
        </div>

        <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
    </div>
</nav>

{% include 'store/snippets/auth.html' %}